import os
import secrets
from PIL import Image
from flask import url_for
from flask_mail import Message
from flask_blog import app, mail

def save_picture(form_picture):
    """Saves user's new profile picture to our file system"""
    # Save photos with random filenames generated by secrets module
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = random_hex + f_ext
    # Get the full path of the profile picture with new filename
    picture_path = os.path.join(app.root_path, 'static/profile_pics', picture_fn)
    # Save resized picture to the picture_path
    resized_image = Image.open(form_picture)
    resized_image.thumbnail((125, 125))
    resized_image.save(picture_path)
    return picture_fn

def send_reset_email(user):
    token = user.get_reset_token()
    sender = str(os.environ.get("MAIL_USERNAME")) + '@gmail.com'
    msg = Message(subject='Password Reset Request',
        sender=sender,
        recipients=[user.email])
    msg.body = f'''To Reset your password, visit the following link:
{url_for('users.reset_token', token=token, _external=True)}
    

If you did not make this request, simply ignore this email. No changes will be made.
'''
    mail.send(msg)
