import os
import secrets
from PIL import Image
from flask import render_template, url_for, flash, redirect, request, abort
from flask_blog import app, db, bcrypt # these come from __init__.py
from flask_blog.forms import RegistrationForm, LoginForm, UpdateAccountForm, PostForm
from flask_blog.models import User, Post
from flask_login import login_user, current_user, logout_user, login_required

@app.route('/') # create home route. Browser will display whatever is returned from the following function
@app.route('/home') # make it so / and /home go to the same place
def home():
    """This route is the home/default landing page for website and can be accessed with '/' or '/home' """
    posts = Post.query.all()
    return render_template('home.html', posts=posts) # we can now access this variable in the template using arg name 'posts'

@app.route('/about')
def about():
    return render_template('about.html', title='About')

@app.route('/register', methods=['GET', 'POST'])
def register():
    """This route is where users register for an account."""
    if current_user.is_authenticated:
        return redirect(url_for('home'))
    form = RegistrationForm()
    if form.validate_on_submit(): # if the form was valid when it was submitted:
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in.', 'success')
        return redirect(url_for('login'))
    return render_template('register.html', title='Register', form=form)

@app.route('/login', methods=['GET', 'POST'])
def login():
    """This route is where users login"""
    if current_user.is_authenticated:
        return redirect(url_for('home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        # Check if user exists & the password is valid. If so, login. Otherwise, flash error.
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('home'))
        else:
            flash('Login unsuccessful. Please check email & password', 'danger')
    return render_template('login.html', title='Login', form=form)

@app.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('home'))

def save_picture(form_picture):
    """Saves user's new profile picture to our file system"""
    # Save photos with random filenames generated by secrets module
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = random_hex + f_ext
    # Get the full path of the profile picture with new filename
    picture_path = os.path.join(app.root_path, 'static/profile_pics', picture_fn)
    # Save resized picture to the picture_path
    resized_image = Image.open(form_picture)
    resized_image.thumbnail((125, 125))
    resized_image.save(picture_path)
    return picture_fn

@app.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    """This route is where users can update their username, email address, and profile picture."""
    form = UpdateAccountForm()
    # Run validations for the form and if the new username/email is valid, update the DB with the new user info.
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('account'))
    # if this is a GET request (meaning browser is just pulling the form, not submitting), auto-populate the fields with the user's existing info
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file) # DB call
    # Also return image_file so we can reference that in our template
    return render_template('account.html', title='Account', image_file=image_file, form=form)

@app.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    """This route is where users will add new posts to the blog."""
    form = PostForm()
    if form.validate_on_submit():
        # create instance of Post class w/ this post's content. I could have expressed the 'user_id=current_user' attribute as 'author=current_user' instead, since it's backref to class User.
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash("Your post has been created!", 'success')
        return redirect(url_for('home'))
    return render_template('create_post.html', title='New Post', form=form, legend_name='New Post')

@app.route('/post/<int:post_id>')
def post(post_id):
    # grab the post from the db. If it doesn't exist, return 404 error ('page doesn't exist')
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)

@app.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    """This route is where users can modify their existing posts """
    # grab the post from the db. If it doesn't exist, return 404 error ('page doesn't exist')
    post = Post.query.get_or_404(post_id)
    # Ensure the editor is actually the author of the post
    if post.author != current_user:
        abort(403) # 403 is HTTP response for a forbidden route.
    form = PostForm()
    # If it's a POST request (meaning user submitted the form), update DB if the changes are valid.
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated', 'success')
        return redirect(url_for('post', post_id=post.id))
    # Otherwise (GET request), pre-populate form with existing post data
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post', form=form, legend_name='Update Post')
